### ISSUE TITLE
[`v2` Regression] Broken execution if `run` contains complex newlines (?)

### ISSUE THREAD

**Issue by whisperity** [xu-cheng/texlive-action#12] opened 2023-10-07 14:41 UTC
Changing from `/full@v1` to `@v2` but leaving the `run:` part intact in my existing code that used this action, the build in the CI broke (about 30 minutes ago). The output was the following:

```
> Run xu-cheng/texlive-action@v2
  with:
    scheme: full
    run: echo "CPU count: $(nproc)"
  
  echo "::group::Package install"
    apk add    \
      make     \
      inkscape \
      qpdf
  echo "::endgroup::"
  
  echo "::group::Third-party support tool versions"
    make     --version
    inkscape --version
    qpdf     --version
  echo "::endgroup::"
  
  echo "::group::Prepare Build directory"
    mkdir -pv ./Build
    chmod -v 777 ./Build
  echo "::endgroup::"
  
  echo "::group::Project configuration"
    make help
  echo "::endgroup::"
  
  echo "::group::Build: Thesis"
    make thesis
  echo "::endgroup::"
  
  
  env:
    BUILD_DIR: Build
    DISPLAY_DIR: Display
    PRINT_DIR: Print
> Run "${GITHUB_ACTION_PATH}/action.sh" \
  "${GITHUB_ACTION_PATH}/action.sh" \
    "full" \
    "" \
    "" \
    "echo "CPU count: $(nproc)"
  
  echo "::group::Package install"
    apk add    \
      make     \
      inkscape \
      qpdf
  echo "::endgroup::"
  
  echo "::group::Third-party support tool versions"
    make     --version
    inkscape --version
    qpdf     --version
  echo "::endgroup::"
  
  echo "::group::Prepare Build directory"
    mkdir -pv ./Build
    chmod -v 777 ./Build
  echo "::endgroup::"
  
  echo "::group::Project configuration"
    make help
  echo "::endgroup::"
  
  echo "::group::Build: Thesis"
    make thesis
  echo "::endgroup::"
  "
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    BUILD_DIR: Build
    DISPLAY_DIR: Display
    PRINT_DIR: Print
docker run --rm -e BIBINPUTS -e BSTINPUTS -e MFINPUTS -e TEXINPUTS -e TFMFONTS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_REPOSITORY_OWNER_ID -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_REPOSITORY_ID -e GITHUB_ACTOR_ID -e GITHUB_ACTOR -e GITHUB_TRIGGERING_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKFLOW_REF -e GITHUB_WORKFLOW_SHA -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e GITHUB_STATE -e GITHUB_OUTPUT -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_ENVIRONMENT -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v /var/run/docker.sock:/var/run/docker.sock -v /home/runner:/home/runner -v /home/runner/work/_temp/_runner_file_commands/set_env_a7590604-af90-40de-935b-64424ac2eb2c:/home/runner/work/_temp/_runner_file_commands/set_env_a7590604-af90-40de-935b-64424ac2eb2c -v /home/runner/work/_temp/_runner_file_commands/set_output_a7590604-af90-40de-935b-64424ac2eb2c:/home/runner/work/_temp/_runner_file_commands/set_output_a7590604-af90-40de-935b-64424ac2eb2c -v /home/runner/work/_temp/_runner_file_commands/step_summary_a7590604-af90-40de-935b-64424ac2eb2c:/home/runner/work/_temp/_runner_file_commands/step_summary_a7590604-af90-40de-935b-64424ac2eb2c -v /home/runner/work/_temp/_runner_file_commands/add_path_a7590604-af90-40de-935b-64424ac2eb2c:/home/runner/work/_temp/_runner_file_commands/add_path_a7590604-af90-40de-935b-64424ac2eb2c -v /home/runner/work/PhD/PhD:/home/runner/work/PhD/PhD -w /home/runner/work/PhD/PhD ghcr.io/xu-cheng/texlive-full:latest /bin/bash -eo pipefail -c -- echo CPU
Unable to find image 'ghcr.io/xu-cheng/texlive-full:latest' locally
latest: Pulling from xu-cheng/texlive-full
96526aa774ef: Already exists
cd2d8fe40b5e: Pulling fs layer
4b07e316e538: Pulling fs layer
cd2d8fe40b5e: Verifying Checksum
cd2d8fe40b5e: Download complete
cd2d8fe40b5e: Pull complete
4b07e316e538: Verifying Checksum
4b07e316e538: Download complete
4b07e316e538: Pull complete
Digest: sha256:b11cb96a30ff54f17f6f5f3a76479519061aa97cd00deafca4f4626a5348c570
Status: Downloaded newer image for ghcr.io/xu-cheng/texlive-full:latest
CPU
```

It seems there is an escape issue or an eager quotation that breaks the existing logic. Oddly enough, not even the first `echo` command ran fully. It just said `CPU` and immediately exited, with a **success**.

![Screenshot from GitHub Actions. The fact that "Create Debug artefact" and "Kill job if LaTeX build failed" steps were skipped shows that `texlive-action` exited with **SUCCESS**.](https://github.com/xu-cheng/texlive-action/assets/1969470/776c83a6-a8bd-4125-b1e0-bdebbbbe22d3)

Reverting to **`/full@v1`** with the same input code restored proper execution:

```
Run xu-cheng/texlive-action/full@v1
/usr/bin/docker run --name ghcrioxuchengtexlivefulllatest_3dcf79 --label 94351b --workdir /github/workspace --rm -e "BUILD_DIR" -e "BIB_DIR" -e "DISPLAY_DIR" -e "PRINT_DIR" -e "MAIN_LANGUAGE_ID" -e "ALT_LANGUAGE_ID" -e "MONOSPACE_FONT" -e "INPUT_RUN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/bin/bash" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/PhD/PhD":"/github/workspace" ghcr.io/xu-cheng/texlive-full:latest  "-eo" "pipefail" "-c" "echo \"CPU count: $(nproc)\"

echo \"::group::Package install\"
  apk add    \
    make     \
    inkscape \
    qpdf
echo \"::endgroup::\"
```

**Comment by xu-cheng** [comment] 2023-10-07 17:40
Please show a reproducible minimal example along with the link to full action running log. Thanks.

**Comment by olifre** [comment] 2023-10-07 18:00
I've been also hit by this — here is a reproducible minimal example:
https://github.com/olifre/texlive-text/blob/3733d2fbb47f3d802b5b9e21cb849148430b1025/.github/workflows/test.yml

Workflow log:
https://github.com/olifre/texlive-text/actions/runs/6442659806/job/17493710691

**Comment by xu-cheng** [comment] 2023-10-09 21:37
Should be fixed by the latest commit. Please check.

**Closed as completed by xu-cheng** 2023-10-09 21:37 UTC

**Comment by olifre** [comment] 2023-10-10 00:08
Indeed, that fixes it for me! 
Successful workflow run:
https://github.com/olifre/texlive-text/actions/runs/6442659806/job/17543950873
Many thanks, using environment variables looks like a great approach :+1: . 

@whisperity Does it also fix your issue?

**Comment by whisperity** [comment] 2023-10-10 08:10
Can confirm, thank you very much!
